logging:
  level:
    ca.uhn.fhir: info
    org.apache.camel: info
    org.ehrbase.fhirbridge: debug
    org.hibernate: info
    org.openehealth.ipf: debug
    org.quartz: info
    org.springframework: info
    org.springframework.boot: info