fhir-bridge:
  ehrbase:
    base-url: http://localhost:8080/ehrbase/rest/openehr/v1/
spring:
  application:
    name: FHIR Bridge PoC
  batch:
    job:
      enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate.search.default.indexBase: ${java.io.tmpdir}/fhir-bridge-poc/lucene
      hibernate.search.lucene_version: LUCENE_CURRENT
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
ipf:
  atna:
    audit-enabled: true
    audit-repository-host: localhost
    audit-repository-port: 3001
server:
  port: 8888
  servlet:
    context-path: /fhir-bridge-poc
logging:
  level:
    ca.uhn.fhir: warn
    org.apache.camel: warn
    org.hibernate: warn
    org.openehealth.ipf: warn
    org.quartz: warn
    org.springframework: warn
    org.springframework.boot: warn