spring:
  application:
    name: FHIR Bridge PoC
  jpa:
    open-in-view: false
server:
  servlet:
    context-path: /fhir-bridge-poc
logging:
  level:
    ca.uhn.fhir: warn
    org.apache.camel: warn
    org.hibernate: warn
    org.openehealth.ipf: warn
    org.quartz: warn
    org.springframework: warn
    org.springframework.boot: warn
