fhir-bridge:
  ehrbase:
    base-url: http://localhost:8080/ehrbase/rest/openehr/v1/
    security:
      type: basic_auth
      username: myuser
      password: myPassword432
    template:
      prefix: classpath:/opt/
  composition:
    debug: false
    output-directory: "src/main/resources/"
spring:
  application:
    name: FHIR Bridge
  batch:
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.search.enabled: true
      hibernate.search.backend.type: lucene
      hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiLuceneAnalysisConfigurer
      hibernate.search.backend.directory.type: local-filesystem
      hibernate.search.backend.directory.root: ${java.io.tmpdir}/fhir-bridge/lucenefiles
      hibernate.search.backend.lucene_version: lucene_current
  liquibase:
    database-change-log-table: DATABASE_CHANGELOG
    database-change-log-lock-table: DATABASE_CHANGELOG_LOCK
    change-log: classpath:/db/changelog/db.changelog-master.xml
  messages:
    basename: messages/messages
    use-code-as-default-message: true
ipf:
  atna:
    audit-enabled: true
    audit-repository-host: localhost
    audit-repository-port: 3001
  fhir:
    fhir-version: r4
server:
  port: 8888
  servlet:
    context-path: /fhir-bridge
logging:
  level:
    ca.uhn.fhir: warn
    com.zaxxer.hikari: warn
    liquibase: warn
    org.apache.camel: warn
    org.hibernate: warn
    org.openehealth.ipf: warn
    org.quartz: warn
    org.springframework: warn
    org.springframework.boot: warn
