spring:
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
logging:
  level:
    ca.uhn.fhir: warn
    org.apache.camel: warn
    org.ehrbase.fhirbridge: warn
    org.hibernate: warn
    org.openehealth.ipf: warn
    org.quartz: warn
    org.springframework: warn
    org.springframework.boot: warn
    org.springframework.security: trace
