# @formatter:off

#
# FHIR Bridge Properties
#
fhir-bridge:
  # CORS Properties
  cors:
    allow-credentials: false
    allowed-headers: '*'
    allowed-methods: '*'
    allowed-origins: '*'
  # Debug Properties
  debug:
    enabled: false
    mapping-output-directory: ${java.io.tmpdir}/mappings
  # EHRbase Properties
  ehrbase:
    base-url: http://localhost:8080/ehrbase/rest/openehr/v1/
    security:
      type: basic_auth
      username: myuser
      password: myPassword432
    template:
      prefix: classpath:/opt/
  # Security Properties
  security:
    authentication-type: none
#    basic:
#      username:
#      password:
#    oauth2:
#      jwk-set-uri:

#
# Spring Properties
#
spring:
  application:
    name: FHIR Bridge
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  # Batch Properties
  batch:
    job:
      enabled: false
  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.default.indexBase: ${java.io.tmpdir}/fhir-bridge/lucenefiles
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.lucene_version: LUCENE_CURRENT
  # Liquibase Properties
  liquibase:
    database-change-log-table: DATABASE_CHANGELOG
    database-change-log-lock-table: DATABASE_CHANGELOG_LOCK
    change-log: classpath:/db/changelog/db.changelog-master.xml
  messages:
    basename: messages/messages
    use-code-as-default-message: true
ipf:
  atna:
    audit-enabled: false
#    audit-repository-host:
#    audit-repository-port:
  fhir:
    fhir-version: r4
server:
  port: 8888
  servlet:
    context-path: /fhir-bridge
logging:
  level:
    ca.uhn.fhir: warn
    com.zaxxer.hikari: warn
    liquibase: warn
    org.apache.camel: warn
    org.hibernate: warn
    org.openehealth.ipf: warn
    org.quartz: warn
    org.springframework: warn
    org.springframework.boot: warn
